<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.5" xml:lang="en-US">
  <compounddef id="classsisi4s_1_1Exception" kind="class" language="C++" prot="public" abstract="yes">
    <compoundname>sisi4s::Exception</compoundname>
    <includes refid="Exception_8hpp" local="no">Exception.hpp</includes>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classsisi4s_1_1Exception_1ab48c48f2fbd5b73109df6eecb60f3b03" prot="public" static="no" const="no" explicit="no" inline="no" virt="pure-virtual">
        <type>std::string</type>
        <definition>virtual std::string sisi4s::Exception::getMessage</definition>
        <argsstring>()=0</argsstring>
        <name>getMessage</name>
        <qualifiedname>sisi4s::Exception::getMessage</qualifiedname>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/runner/work/sisi4s/sisi4s/src/util/Exception.hpp" line="16" column="23"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <collaborationgraph>
      <node id="1">
        <label>sisi4s::Exception</label>
        <link refid="classsisi4s_1_1Exception"/>
      </node>
    </collaborationgraph>
    <location file="/home/runner/work/sisi4s/sisi4s/src/util/Exception.hpp" line="14" column="1" bodyfile="/home/runner/work/sisi4s/sisi4s/src/util/Exception.hpp" bodystart="14" bodyend="17"/>
    <listofallmembers>
      <member refid="classsisi4s_1_1Exception_1ab48c48f2fbd5b73109df6eecb60f3b03" prot="public" virt="pure-virtual"><scope>sisi4s::Exception</scope><name>getMessage</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
